import Head from 'next/head'
import About from '../components/About'
import Main from '../components/Main'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import Contact from './../components/Contact'
import { getAllProjects } from '../components/lib/helper'

export const getStaticProps = async () => {
	const projects = await getAllProjects()
	return { props: { projects } }
}

export default function Home({ projects }) {
	return (
		<div>
			<Head>
				<title>Four | Front-end Developer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo.png" />
			</Head>
			<Main />
			<About />
			<Skills />
			<Projects projects={projects} />
			<Contact />
		</div>
	)
}
